export const SignUpData={
    FirstName:"First Name",
    LastName:"Last Name",
    Email:"Email ID",
    PhoneNumber:"Phone Number",
    DateOfBirth:"Date of Birth",
    Password:"Password",
    ConfirmPassword:"Confirm Password",
    UserName:"User Name",
    UserPassword:"User Password",
    SignIn:"SignIn",
    SignUp:"SignUp",
    Page1:"Page1",
    Page2:"Page2",
    Page3:"Page3",
    Page4:"Page4",
    Page5:"Page5",
}